---
name: Unit Test

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: List to troubleshoot
        run: pwd

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          pip install -e .

      - name: Setup dockerised Redis
        run: make dev

      - name: Unit test
        run: |
          python -m unittest discover ./test/
